### ISSUE TITLE
Peer dependencies outdated

### ISSUE THREAD

**Issue by LXIF** [softwarecurator/svelte-wagmi#10]
Hi! Was trying to set this up with the most current versions of viem and @wagmi/core, which threw an error about "Missing "./providers/public" specifier in "@wagmi/core" package". I then had a look at your package.json and took the versions from there. The application now loads fine, but wagmiLoaded doesn't turn true. Is this a bug or am I missing something?

**Comment by softwarecurator** [comment]
yeah, i will have to rewrite certain areas of the package to work with wagmi/viem v2

**Comment by softwarecurator** [comment]
@LXIF this is now updated with 1.0.0!
