### ISSUE TITLE
Connector not connected, when trying to perform a writeContract call using @wagmi/core

### ISSUE THREAD

**Issue by hardingjam** [softwarecurator/svelte-wagmi#11]
Are you able to show an example of performing a transaction using @wagmi/core, using the created config shown in your examples?

**Comment by softwarecurator** [comment]
> Are you able to show an example of performing a transaction using @wagmi/core, using the created config shown in your examples?
> 
> 
> 
> 
> 
> 

can you provide a code snippet?

**Comment by softwarecurator** [comment]
@hardingjam Once svelte-wagmi is setup you can call the `wagmi/core` functions like `writeContract` just like any normal JS function using the `$wagmiConfig` store from the package.

Here's a quick example

```svelte
<script>
import { writeContract } from '@wagmi/core';
import { wagmiConfig } from 'svelte-wagmi';

async function write() {
	const args = ['0x000000000000000000000000000000000000dEaD', 100000000];
	const tx = await writeContract($wagmiConfig, {
		abi: USDC,
		address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
		functionName: 'transfer',
		args
	});

	console.log(tx);
}
</script>
```

**Comment by hardingjam** [comment]
> @hardingjam Once svelte-wagmi is setup you can call the `wagmi/core` functions like `writeContract` just like any normal JS function using the `$wagmiConfig` store from the package.
> 
> Here's a quick example
> 
> ```svelte
> <script>
> import { writeContract } from '@wagmi/core';
> import { wagmiConfig } from 'svelte-wagmi';
> 
> async function write() {
> 	const args = ['0x000000000000000000000000000000000000dEaD', 100000000];
> 	const tx = await writeContract($wagmiConfig, {
> 		abi: USDC,
> 		address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
> 		functionName: 'transfer',
> 		args
> 	});
> 
> 	console.log(tx);
> }
> </script>
> ```

Thanks, I'll give this a try once I can get the config set up correctly.

**Comment by hardingjam** [comment]
> @hardingjam Once svelte-wagmi is setup you can call the `wagmi/core` functions like `writeContract` just like any normal JS function using the `$wagmiConfig` store from the package.
> 
> Here's a quick example
> 
> ```svelte
> <script>
> import { writeContract } from '@wagmi/core';
> import { wagmiConfig } from 'svelte-wagmi';
> 
> async function write() {
> 	const args = ['0x000000000000000000000000000000000000dEaD', 100000000];
> 	const tx = await writeContract($wagmiConfig, {
> 		abi: USDC,
> 		address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
> 		functionName: 'transfer',
> 		args
> 	});
> 
> 	console.log(tx);
> }
> </script>
> ```

Thanks, I was able to solve this using the example in your repo. There were some conflicts with an existing web3Modal implementation in my code 👍

**Comment by softwarecurator** [comment]
`1.0.3` now exposes wagmiConfig from package
