### ISSUE TITLE
Which config object should be passed to writeContract calls? wagmiConfig not exported by index.ts

### ISSUE THREAD

**Issue by hardingjam** [softwarecurator/svelte-wagmi#12]
In your example, you pass wagmiConfig from the stores into the writeContract calls, as the first argument

https://github.com/softwarecurator/svelte-wagmi/blob/main/src/routes/%2Bpage.svelte

This store is initialised in your wagmi.ts file and exported, but not exposed by index.ts as part of the package. It's not immediately clear which config object should be passed to any wagmi contract calls. Can you perhaps elaborate on the intended usage?

**Comment by hardingjam** [comment]
Here is where I initiate the stores:

`

	// Svelte-wagmi imports
	import {
		connected,
		wagmiLoaded,
		chainId,
		signerAddress,
		loading,
		web3Modal,
		defaultConfig,
		configuredConnectors,
		WC,
		disconnectWagmi
	} from 'svelte-wagmi';

	import { onMount } from 'svelte';
	// import { configureChains } from '@wagmi/core';
	import {
		mainnet,
		polygon,
		polygonMumbai,
		arbitrum,
		sepolia,
		arbitrumSepolia
	} from '@wagmi/core/chains';

	import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query';
	import { PUBLIC_WALLETCONNECT_ID, PUBLIC_ALCHEMY_PROJECT_ID } from '$env/static/public';

	import { targetNetwork, wagmiConfig } from '$lib/stores';

	import { ipfsLoggedIn } from '$lib/stores';
	import { walletConnect, injected } from '@wagmi/connectors';

	const chains = [polygon, polygonMumbai, arbitrum, sepolia, mainnet, arbitrumSepolia];

	onMount(async () => {
		const erckit = defaultConfig({
			appName: 'myApp',
			alchemyId: PUBLIC_ALCHEMY_PROJECT_ID,
			walletConnectProjectId: PUBLIC_WALLETCONNECT_ID,
			chains: chains,
			connectors: [
				injected(),
				walletConnect({
					projectId: PUBLIC_WALLETCONNECT_ID
				})
			]
		});

		await erckit.init();
	});

`

My question is  - is there anything exported from svelte-wagmi that can be passed into wagmi contract calls as the config value, or do I need to construct that elsewhere?

**Comment by hardingjam** [comment]
The object you need to pass as the first arg to wagmi contract calls is $web3Modal.wagmiConfig

**Comment by softwarecurator** [comment]
1.0.3 now exposes wagmiConfig
