### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by xpluscal** [softwarecurator/svelte-wagmi#17]
When running the latest version I get the error "process is not defined" with basically any import from the package.
Bummer, love your package!

**Comment by hardingjam** [comment]
> When running the latest version I get the error "process is not defined" with basically any import from the package. Bummer, love your package!

I was able to fix this by adding in vite.config.ts

```
define: {
		"process.env": {}
	}
```

**Comment by xpluscal** [comment]
resolved thank you. @softwarecurator maybe we could add this to readme? thanks :)

**Comment by softwarecurator** [comment]
add this in `1.0.7` thanks for the help!
