### ISSUE TITLE
StreamMiddleware - Unknown response id...

### ISSUE THREAD

**Issue by chtmorris** [softwarecurator/svelte-wagmi#2]
Hey @softwarecurator - me again! I'm not able to connect to WalletConnect.

In Chrome I have MetaMask installed and on page load I'm getting the error:
_StreamMiddleware - Unknown response id "2894685863"_

Interestingly, on another browser where I don't have MetaMask installed I'm getting no error messages, but clicking the Connect to Ethereum button does nothing.

In Visual Studio I'm also getting the error - Expected 0 arguments, but got 1 - inside `await WC()`:

```
async function connectToEthereum() {
		await WC('Sign in to the app with Ethereum');
}
```

Any ideas?

**Comment by softwarecurator** [comment]
try removing that parameter docs aren't totally up to date also what version of sveltekit are you using?

**Comment by chtmorris** [comment]
Removing that parameter makes no difference. Still nothing when I click on the button.

 `"@sveltejs/kit": "^1.5.0"`

**Comment by softwarecurator** [comment]
update `svelte-wagmi` to `0.3.1`

also heres a [demo repo](https://github.com/softwarecurator/sveltekit-wagmi-example)
