### ISSUE TITLE
web3modal is undefined

### ISSUE THREAD

**Issue by tunnckoCore** [softwarecurator/svelte-wagmi#6]
I have a connect button 

```html
<script>
	import {
		web3Modal,
		connected,
		disconnectWagmi,
		signerAddress,
	} from 'svelte-wagmi';

	import { fetchEnsName, fetchEnsAvatar } from '@wagmi/core';

	const connect = async () => {
		if (!$connected) {
			console.log('web3modal:', $web3Modal); // => undefined
			$web3modal.openModal();
		}
	};
</script>
```

deps

```json
"@wagmi/core": "^1.3.4",
"svelte-wagmi": "^0.3.3",
"viem": "^1.2.9"
"@sveltejs/kit": "^1.20.4",
"svelte": "^4.0.0",
```

Your demo app repo doesn't seem to work either.
https://github.com/softwarecurator/svelte-wagmi-demo-app

**Comment by tunnckoCore** [comment]
Also tried to disable prerendering and ssr on `+page.js`, and enable it to be only CSR.. but still fails.

```js
export const csr = true;
export const ssr = false;
export const prerender = false;
```

cc @softwarecurator

**Comment by tunnckoCore** [comment]
Good to mention that with `connection(1)` method it works fine. Seems like a problem specifically with the web3modal.

Using injected wallet to connect is enough and fine to me for now.

**Comment by softwarecurator** [comment]
Will update that demo app soon does this [example work for you?](https://github.com/softwarecurator/svelte-wagmi/blob/0.3.4/src/routes/%2Bpage.svelte)

also updated some deps on `0.3.4`

I plan on updating some core features to this package soon that should allow more flexibility in what you wanna build
