### ISSUE TITLE
web3Modal / Wallet Connect V3

### ISSUE THREAD

**Issue by xpluscal** [softwarecurator/svelte-wagmi#9]
With Wallet Connect having announced a stable V3, it might make sense to consider switching over to V3 (given that they might decide to deprecate support).

**Comment by softwarecurator** [comment]
Plan on updating this with wagmi v2 and svelte 5 soon

**Comment by ByteAtATime** [comment]
> Plan on updating this with wagmi v2 and svelte 5 soon

Hey! I've made a very similar package for Svelte 5. I just realized your project existed, so I was wondering if you'd be down to collab. Repo is here: https://github.com/ByteAtATime/wagmi-svelte

**Comment by softwarecurator** [comment]
> > Plan on updating this with wagmi v2 and svelte 5 soon
> 
> Hey! I've made a very similar package for Svelte 5. I just realized your project existed, so I was wondering if you'd be down to collab. Repo is here: https://github.com/ByteAtATime/wagmi-svelte

hey just checked it out would love to collab!

**Comment by ByteAtATime** [comment]
> > > Plan on updating this with wagmi v2 and svelte 5 soon
> > 
> > 
> > Hey! I've made a very similar package for Svelte 5. I just realized your project existed, so I was wondering if you'd be down to collab. Repo is here: https://github.com/ByteAtATime/wagmi-svelte
> 
> hey just checked it out would love to collab!

Do you have a preferred contact method? If you want, please email me at `byteatatime@proton.me` to discuss this further.

(not sure if this is an appropriate use of the issues discussion, but oh well)
